package com.pes.facialparalysis.ui.theme.components

import androidx.compose.animation.core.animateFloatAsState
import androidx.compose.animation.core.tween
import androidx.compose.foundation.BorderStroke
import androidx.compose.foundation.Canvas
import androidx.compose.foundation.background
import androidx.compose.foundation.layout.*
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.Info
import androidx.compose.material3.*
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.geometry.Offset
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import com.pes.facialparalysis.ml.FaiCalculator
import com.pes.facialparalysis.ml.LimeExplainer
import com.pes.facialparalysis.ui.theme.AppColors
import com.google.mediapipe.tasks.components.containers.NormalizedLandmark
import androidx.compose.runtime.getValue

/**
 * The one place the app's mandatory AI-disclosure wording lives, so it stays consistent
 * everywhere a prediction is shown and never drifts into diagnostic-sounding language.
 */
object AiDisclosure {
    const val SHORT = "AI-estimated grade — not a medical diagnosis."
    const val FULL = "This result is generated by an AI model and may be inaccurate. It is not " +
        "a medical diagnosis and does not replace professional care. Please discuss this result " +
        "with a qualified healthcare professional."
}

@Composable
fun DisclaimerBanner(modifier: Modifier = Modifier, text: String = AiDisclosure.FULL) {
    Card(
        modifier = modifier.fillMaxWidth(),
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(containerColor = AppColors.SurfaceMuted),
        border = BorderStroke(1.dp, AppColors.Border),
        elevation = CardDefaults.cardElevation(defaultElevation = 0.dp)
    ) {
        Row(modifier = Modifier.padding(14.dp)) {
            Icon(
                imageVector = Icons.Filled.Info,
                contentDescription = null,
                tint = AppColors.TextSecondary,
                modifier = Modifier.size(16.dp)
            )
            Spacer(modifier = Modifier.width(10.dp))
            Text(
                text = text,
                fontSize = 12.sp,
                lineHeight = 16.sp,
                color = AppColors.TextSecondary,
                modifier = Modifier.align(Alignment.CenterVertically)
            )
        }
    }
}

/** Prominent banner mandated for every screen that shows an AI explanation. */
@Composable
fun NotADiagnosisBanner(modifier: Modifier = Modifier) {
    Card(
        modifier = modifier.fillMaxWidth(),
        shape = RoundedCornerShape(10.dp),
        colors = CardDefaults.cardColors(containerColor = AppColors.Warning.copy(alpha = 0.14f)),
        border = BorderStroke(1.dp, AppColors.Warning.copy(alpha = 0.4f)),
        elevation = CardDefaults.cardElevation(defaultElevation = 0.dp)
    ) {
        Column(modifier = Modifier.padding(14.dp)) {
            Text(
                text = "AI EXPLANATION — NOT A DIAGNOSIS",
                fontSize = 12.sp,
                fontWeight = FontWeight.Bold,
                letterSpacing = 0.5.sp,
                color = AppColors.Warning
            )
            Spacer(modifier = Modifier.height(6.dp))
            Text(
                text = "This explanation describes how the AI interpreted the scan. It may be " +
                    "incorrect and does not confirm whether you have or do not have facial paralysis. " +
                    "This tool does not replace assessment by a qualified healthcare professional.",
                fontSize = 12.sp,
                lineHeight = 16.sp,
                color = AppColors.TextPrimary
            )
        }
    }
}

/** Bars showing each region's LIME-fitted contribution to the model's predicted grade. */
@Composable
fun RegionImportanceBars(
    importance: List<LimeExplainer.RegionImportance>,
    modifier: Modifier = Modifier
) {
    Card(
        modifier = modifier.fillMaxWidth(),
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(containerColor = AppColors.Surface),
        border = BorderStroke(1.dp, AppColors.Border),
        elevation = CardDefaults.cardElevation(defaultElevation = 0.dp)
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Text(
                text = "AI explanation of important facial regions",
                fontSize = 13.sp,
                fontWeight = FontWeight.SemiBold,
                color = AppColors.TextPrimary
            )
            Spacer(modifier = Modifier.height(4.dp))
            Text(
                text = "How much each region's visibility pushed the model toward its predicted grade (LIME).",
                fontSize = 11.sp,
                color = AppColors.TextSecondary
            )
            Spacer(modifier = Modifier.height(12.dp))
            importance.forEach { region ->
                RegionImportanceRow(region)
                Spacer(modifier = Modifier.height(10.dp))
            }
        }
    }
}

@Composable
private fun RegionImportanceRow(region: LimeExplainer.RegionImportance) {
    val animatedProgress by animateFloatAsState(
        targetValue = region.normalizedMagnitude.toFloat(),
        animationSpec = tween(durationMillis = 500),
        label = "importance"
    )
    val barColor = when (region.direction) {
        LimeExplainer.Direction.SUPPORTS -> AppColors.Primary
        LimeExplainer.Direction.OPPOSES -> Color(0xFFB5651D)
        LimeExplainer.Direction.NEGLIGIBLE -> AppColors.TextSecondary.copy(alpha = 0.4f)
    }
    val label = when (region.direction) {
        LimeExplainer.Direction.SUPPORTS -> "Higher contribution"
        LimeExplainer.Direction.OPPOSES -> "Opposed prediction"
        LimeExplainer.Direction.NEGLIGIBLE -> "Low contribution"
    }
    Column {
        Row(horizontalArrangement = Arrangement.SpaceBetween, modifier = Modifier.fillMaxWidth()) {
            Text(region.displayLabel, fontSize = 13.sp, color = AppColors.TextPrimary)
            Text(label, fontSize = 11.sp, color = AppColors.TextSecondary)
        }
        Spacer(modifier = Modifier.height(4.dp))
        Box(
            modifier = Modifier
                .fillMaxWidth()
                .height(7.dp)
                .clip(RoundedCornerShape(4.dp))
                .background(AppColors.SurfaceMuted)
        ) {
            Box(
                modifier = Modifier
                    .fillMaxHeight()
                    .fillMaxWidth(animatedProgress.coerceIn(0.02f, 1f))
                    .clip(RoundedCornerShape(4.dp))
                    .background(barColor)
            )
        }
    }
}

/** Small pill flagging content that is illustrative demo data, not a real recorded assessment. */
@Composable
fun DemoDataBadge(modifier: Modifier = Modifier) {
    Box(
        modifier = modifier
            .clip(RoundedCornerShape(6.dp))
            .background(AppColors.Warning.copy(alpha = 0.14f))
            .padding(horizontal = 8.dp, vertical = 3.dp)
    ) {
        Text(
            text = "DEMO DATA",
            fontSize = 10.sp,
            fontWeight = FontWeight.Bold,
            letterSpacing = 0.5.sp,
            color = AppColors.Warning
        )
    }
}

@Composable
fun ConfidenceBars(
    probabilities: Map<Int, Double>,
    selectedGrade: Int,
    modifier: Modifier = Modifier,
    title: String = "Model confidence by grade"
) {
    Card(
        modifier = modifier.fillMaxWidth(),
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(containerColor = AppColors.Surface),
        border = BorderStroke(1.dp, AppColors.Border),
        elevation = CardDefaults.cardElevation(defaultElevation = 0.dp)
    ) {
        Column(modifier = Modifier.padding(18.dp)) {
            Text(text = title, fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = AppColors.TextPrimary)
            Spacer(modifier = Modifier.height(14.dp))
            probabilities.toSortedMap().forEach { (g, prob) ->
                ConfidenceBarRow(grade = g, probability = prob, isSelected = g == selectedGrade)
                Spacer(modifier = Modifier.height(10.dp))
            }
        }
    }
}

@Composable
private fun ConfidenceBarRow(grade: Int, probability: Double, isSelected: Boolean) {
    val animatedProgress by animateFloatAsState(
        targetValue = probability.toFloat(),
        animationSpec = tween(durationMillis = 600),
        label = "probability"
    )
    val barColor = if (isSelected) AppColors.Primary else AppColors.Primary.copy(alpha = 0.3f)

    Row(verticalAlignment = Alignment.CenterVertically) {
        Text(
            text = "G$grade",
            fontSize = 12.sp,
            fontWeight = if (isSelected) FontWeight.Bold else FontWeight.Medium,
            color = AppColors.TextPrimary,
            modifier = Modifier.width(26.dp)
        )
        Box(
            modifier = Modifier
                .weight(1f)
                .height(7.dp)
                .clip(RoundedCornerShape(4.dp))
                .background(AppColors.SurfaceMuted)
        ) {
            Box(
                modifier = Modifier
                    .fillMaxHeight()
                    .fillMaxWidth(animatedProgress)
                    .clip(RoundedCornerShape(4.dp))
                    .background(barColor)
            )
        }
        Spacer(modifier = Modifier.width(8.dp))
        Text(
            text = "${"%.0f".format(probability * 100)}%",
            fontSize = 12.sp,
            color = AppColors.TextPrimary,
            modifier = Modifier.width(34.dp)
        )
    }
}

/**
 * Draws the real detected landmark points used for the asymmetry measurements, plus a
 * region-asymmetry overlay whose marker size/opacity scales with that region's measured
 * percentage. This is a geometric visualization of real landmark data — explicitly not a
 * model-internal saliency/Grad-CAM map (the on-device model doesn't expose one).
 */
@Composable
fun LandmarkAsymmetryOverlay(
    landmarks: List<NormalizedLandmark>,
    regions: List<FaiCalculator.RegionAsymmetry>,
    modifier: Modifier = Modifier
) {
    val regionIndices = mapOf(
        "eye" to listOf(159, 145, 386, 374),
        "mouth" to listOf(0, 61, 291),
        "brow" to listOf(4, 105, 334),
        "cheek" to listOf(1, 234, 454),
        "jaw" to listOf(152, 172, 397)
    )
    val regionByName = regions.associateBy { it.region }
    val regionColor = mapOf(
        "eye" to Color(0xFF0F6E7A),
        "mouth" to Color(0xFFB5651D),
        "brow" to Color(0xFF4F46E5),
        "cheek" to Color(0xFF9E3535),
        "jaw" to Color(0xFF2E7D4F)
    )

    Canvas(modifier = modifier) {
        // Faint dots for every detected landmark, so the overlay reads as "derived from the
        // full landmark mesh" rather than a handful of cherry-picked points.
        landmarks.forEach { lm ->
            drawCircle(
                color = Color.White.copy(alpha = 0.35f),
                radius = 1.2.dp.toPx(),
                center = Offset(lm.x() * size.width, lm.y() * size.height)
            )
        }

        regionIndices.forEach { (region, indices) ->
            val asymmetry = regionByName[region]?.asymmetryPercent ?: 0.0
            val color = regionColor[region] ?: Color.White
            // Scale visual weight with the actual measured percentage — capped so a single
            // outlier region doesn't blow past the readable range.
            val weight = (asymmetry / 30.0).coerceIn(0.15, 1.0)
            indices.forEach { idx ->
                if (idx < landmarks.size) {
                    val lm = landmarks[idx]
                    val center = Offset(lm.x() * size.width, lm.y() * size.height)
                    drawCircle(
                        color = color.copy(alpha = (0.18 * weight).toFloat()),
                        radius = (10.dp.toPx() * weight).toFloat(),
                        center = center
                    )
                    drawCircle(
                        color = color.copy(alpha = 0.9f),
                        radius = 2.5.dp.toPx(),
                        center = center
                    )
                }
            }
        }
    }
}

/**
 * Landmark importance mapping: highlights each facial region using its LIME-fitted contribution
 * to the model's prediction, so intensity here communicates "influence on the AI's output" — not
 * a claim about where paralysis is present. Regions that opposed the prediction are drawn in a
 * different hue from regions that supported it.
 */
@Composable
fun LimeImportanceOverlay(
    landmarks: List<NormalizedLandmark>,
    importance: List<LimeExplainer.RegionImportance>,
    modifier: Modifier = Modifier
) {
    // Same landmark points LIME actually scored, so the overlay highlights exactly what was tested.
    val regionIndices = LimeExplainer.regionLandmarkIndices
    val importanceByRegion = importance.associateBy { it.region }
    val supportsColor = AppColors.Primary
    val opposesColor = Color(0xFFB5651D)

    Canvas(modifier = modifier) {
        regionIndices.forEach { (region, indices) ->
            val info = importanceByRegion[region] ?: return@forEach
            val color = when (info.direction) {
                LimeExplainer.Direction.SUPPORTS -> supportsColor
                LimeExplainer.Direction.OPPOSES -> opposesColor
                LimeExplainer.Direction.NEGLIGIBLE -> Color.Gray
            }
            val weight = info.normalizedMagnitude.coerceIn(0.1, 1.0)
            indices.forEach { idx ->
                if (idx < landmarks.size) {
                    val lm = landmarks[idx]
                    val center = Offset(lm.x() * size.width, lm.y() * size.height)
                    drawCircle(
                        color = color.copy(alpha = (0.22 * weight).toFloat()),
                        radius = (14.dp.toPx() * weight).toFloat(),
                        center = center
                    )
                }
            }
        }
    }
}

/** List of possible scan-quality factors — a mix of on-device–detected checks and generic,
 * always-worded-as-possible factors that were not specifically verified. */
@Composable
fun PossibleScanIssuesCard(
    detectedFactors: List<String>,
    unverifiedFactors: List<String>,
    modifier: Modifier = Modifier
) {
    Card(
        modifier = modifier.fillMaxWidth(),
        shape = RoundedCornerShape(12.dp),
        colors = CardDefaults.cardColors(containerColor = AppColors.Surface),
        border = BorderStroke(1.dp, AppColors.Border),
        elevation = CardDefaults.cardElevation(defaultElevation = 0.dp)
    ) {
        Column(modifier = Modifier.padding(16.dp)) {
            Text("Could this result be incorrect?", fontSize = 13.sp, fontWeight = FontWeight.SemiBold, color = AppColors.TextPrimary)
            Spacer(modifier = Modifier.height(8.dp))
            if (detectedFactors.isNotEmpty()) {
                Text("Things noticed about this scan:", fontSize = 12.sp, fontWeight = FontWeight.Medium, color = AppColors.TextPrimary)
                Spacer(modifier = Modifier.height(4.dp))
                detectedFactors.forEach { factor ->
                    Text("•  $factor This may have affected the result.", fontSize = 12.sp, color = AppColors.TextPrimary, lineHeight = 16.sp)
                    Spacer(modifier = Modifier.height(4.dp))
                }
                Spacer(modifier = Modifier.height(8.dp))
            }
            Text("Other things that may affect any scan:", fontSize = 12.sp, fontWeight = FontWeight.Medium, color = AppColors.TextSecondary)
            Spacer(modifier = Modifier.height(4.dp))
            unverifiedFactors.forEach { factor ->
                Text("•  $factor", fontSize = 12.sp, color = AppColors.TextSecondary, lineHeight = 16.sp)
                Spacer(modifier = Modifier.height(3.dp))
            }
        }
    }
}
