package com.pes.facialparalysis.data

import androidx.room.Entity
import androidx.room.PrimaryKey

@Entity(tableName = "assessments")
data class AssessmentRecord(
    @PrimaryKey(autoGenerate = true) val id: Int = 0,
    val patientId: Int,
    val timestamp: Long,
    val grade: Int,
    val gradeLabel: String,
    /** Overall facial asymmetry index — average of the 5 region asymmetry percentages below. */
    val faiValue: Double,
    val confidence: Double,
    // --- Digital Twin / XAI fields (added; existing rows default to 0.0 / ""). ---
    val eyeAsymmetry: Double = 0.0,
    val mouthAsymmetry: Double = 0.0,
    val browAsymmetry: Double = 0.0,
    val cheekAsymmetry: Double = 0.0,
    val jawAsymmetry: Double = 0.0,
    /** Comma-separated region display labels ranked by measured asymmetry, e.g. "Left eye region,Left mouth region". */
    val topRegionsCsv: String = "",
    /** Plain-language "why this prediction" text generated by XaiExplainer. */
    val xaiExplanation: String = ""
)